# A docker-compose must always start by the version tag.
# We use "3" because it's the last version at this time.
version: "3.3"
services:
  server:
    image: tls_server
    build: server/
    #networks:
    # front:
    #   ipv4_address: 172.16.238.10
    #network_mode: host
    command: python3 server.py
    #restart: always
    ports:
      - 4433:4433

  client:
    image: tls_client
    build: client/
    #network_mode: host
    #networks:
    # front:
    #   ipv4_address: 172.16.238.11
    command: python3 client.py
    #restart: always
    volumes:
            - $PWD/results:/client/openssl/results
            - $PWD/scripts:/client/scripts
    depends_on:
      - server
    links:
      - server
volumes:
        results:

        #networks:
        #front:
    # use the bridge driver, but enable IPv6
    #driver: bridge
    #ipam:
    # driver: default
    # config:
    #   - subnet: 172.16.238.0/24

