version: "3.3"
services:
  server:
    image: tls_server
    build: server/
    # Run TLS server
    command: python3 server.py
    ports:
      - 4433:4433

  client:
    image: tls_client
    build: client/
    # Run TLS clients with different parameter sets and retrieve resulting charts
    command: python3 client.py && python3 parser.py
    volumes:
            - $PWD/results:/client/openssl/results
            - $PWD/scripts:/client/scripts
    depends_on:
      - server
    links:
      - server
volumes:
        results:

    

